### ISSUE TITLE
accessionWF should not complete if any accessionWF step is waiting

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1965]
**Describe the bug**
Druid gs556yg7381 completed the end-accession step of the accessionWF while preservation-ingest-intitiated was still listed as waiting. The final step of the accessionWF should not be completed unless all previous steps have been completed.

![accession-before-preservation](https://user-images.githubusercontent.com/8975583/80936054-56390b80-8d84-11ea-93d2-2ed555e75a1b.png)
 

**User Impact**
There's a risk of data loss if the accessionWF completes too early, as the last step in the workflow clears the /dor workspace for the druid being processed.

**To Reproduce**
There is no way for a user to deliberately generate this error. The screenshot above shows that it can occur.

**Expected behavior**
The accessionWF does not complete until all steps are complete.

**Additional context**
The preservationIngestWF ran even though preservation-ingest-initiated was listed as waiting. preservation-ingest-initiated is supposed to be completed before the preservationIngestWF begins.

The preservation-ingest-initiated step eventually completed on its own. You can see by the timestamps below that it took another 20 minutes for that to happen.

![late-preservation-ingest](https://user-images.githubusercontent.com/8975583/80936825-a1a0e900-8d87-11ea-88ba-7be1b72dcff3.png)

**Comment by jcoyne** [comment]
@andrewjbtw This happened because preservation-ingest-initiated completed it's work (which was to activate the preservation workflow), but it just hadn't been able to record it's success status (presumably due to network problems).  There is no way that this could have finished out of order.  There is no risk of data loss here.

**Comment by andrewjbtw** [comment]
I thought the logic was set so that accessionWF doesn't complete if any step still doesn't have a status of completed or skipped. I'm glad there was no risk of data loss in this one example, but that doesn't explain why the workflow completed anyway.

**Comment by jcoyne** [comment]
It depends what you mean by "complete".  There are no steps that have preservation-ingest-initiated listed as a prerequisite, so there is no required dependency there.  As far as I know the "completed" status as listed below only shows completed when all steps are in fact completed.   The end-accessioning step is the last step, but just because the last step is complete does not mean the workflow is complete.   The workflow is not-linear. It is a dependency management system, which allows for the possibility of processing things in parallel so long as their pre-requisites are resolved.
<img width="339" alt="Screen Shot 2020-05-04 at 11 31 14 AM" src="https://user-images.githubusercontent.com/92044/80989622-ce421880-8dfa-11ea-83ba-6e91de2398c8.png">

**Comment by andrewjbtw** [comment]
Here's another example: https://argo.stanford.edu/view/ng541pg0667

Three steps are waiting, but end-accession has run and the top level status line says "v2 Accessioned".

But the accessionWF does still have a status of "active" and the blue button to open the object is not active. As far as I can tell, preservationIngestWF actually did run. So accessioning is both complete and not complete, depending on how you measure it.

I can change this ticket to be to show the correct status on the top status line. In this case, the status should not show as "Accessioned". The situation we have is confusing.

**Comment by andrewjbtw** [comment]
I don't think this is still relevant to how the system works, so I'm closing it.
